buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}

allprojects {
    version = project.findProperty('versionName') ?: System.getenv('VERSION_NAME') ?: '1.0.0'
    ext {
        appName = 'GamePingPongTouch'
        gdxVersion = '1.14.2'
    }
}

subprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'
}

configure(subprojects.findAll { it.name != 'android' }) {
    apply plugin: 'java-library'
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    compileJava.options.encoding = 'UTF-8'
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
